import { randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";
import { z } from "zod";
import { canonicalizeProjectCwd, digestTask, isPathInside, validateProjectPlan, validateProjectRelativePath } from "./plan-validator.js";
import { RegistryStore } from "./registry.js";
import { reconcileMilestoneStates } from "./milestone-state.js";
import type { CodexAppServerPort, MilestoneTask } from "./types.js";

const GrantSchema = z.object({ milestone_id:z.string(), thread_id:z.string(), canonical_cwd:z.string(), plan_digest:z.string().length(64), task_digest:z.string().length(64), allowed_paths:z.array(z.string()).min(1), forbidden_paths:z.array(z.string()), sandbox_mode:z.literal("workspace-write"), network_policy:z.literal("disabled"), approval_policy:z.literal("on-request"), granted_at:z.string().datetime(), expires_at:z.string().datetime(), activation_operation_id:z.string().uuid(), status:z.enum(["PREVIEWED","ACTIVE","CONSUMED","REVOKED","EXPIRED"]) }).strict();
type Grant = z.infer<typeof GrantSchema>;
const TTL = 30 * 60 * 1000;
const execFileAsync = promisify(execFile);
const M0_TEMPLATE = ["SPEC.md","PLAN.md","STATUS.md","DECISIONS.md","RISKS.md","THREADS.md","docs","scripts/validate-baseline.ps1",".project-capsule"];
const FORBIDDEN = [".git",".env",".env.*","secrets","production","hardware"];

export class MilestoneActivationService {
  public constructor(private readonly app: CodexAppServerPort, private readonly registry = new RegistryStore(), private readonly now=()=>new Date()) {}
  public async preview(raw: unknown): Promise<Record<string,unknown>> { const ctx=await this.context(raw); const grant=this.grant(ctx,"PREVIEWED"); return { ok:true, confirmation_required:true, summary:`将开始 ${ctx.task.milestone_id}：${ctx.task.name}。只会修改规格、决策、风险、文档与验证脚本；不会执行其他里程碑，也不会访问密钥或生产文件。`, expires_at:grant.expires_at }; }
  public async activate(raw: unknown): Promise<Record<string,unknown>> { const ctx=await this.context(raw); try { const prior=GrantSchema.parse(JSON.parse(await readFile(this.grantPath(ctx.cwd,ctx.task.milestone_id),"utf8"))); if(prior.status==="ACTIVE"&&Date.parse(prior.expires_at)>this.now().getTime()&&prior.plan_digest===ctx.plan.plan_digest&&prior.task_digest===digestTask(ctx.task)&&prior.thread_id===ctx.threadId) return {ok:true,status:"ACTIVE",reused:true,milestone_id:ctx.task.milestone_id}; } catch {} const grant=this.grant(ctx,"ACTIVE"); await this.writeGrant(ctx.cwd,grant); const resumed=await this.app.resumeThread(ctx.threadId); const loaded=await this.app.listLoadedThreadIds({limit:100}); if (!loaded.data.includes(ctx.threadId)) throw new Error("thread resume did not load target thread"); const turn=await this.app.startTurn({threadId:ctx.threadId,cwd:ctx.cwd,approvalPolicy:"on-request",sandboxPolicy:{type:"workspaceWrite",networkAccess:false,writableRoots:ctx.allowed},input:[{type:"text",text:`Execute ${ctx.task.milestone_id}. Follow the project capsule and task card. Work only within the approved scope; do not access forbidden paths, network, Git, secrets, production, or hardware. Stop and request approval for any action outside the approved scope.`,text_elements:[]}]}); void resumed; return {ok:true,status:"ACTIVE",milestone_id:ctx.task.milestone_id,turn_id:turn.id}; }
  public async start(raw: unknown): Promise<Record<string,unknown>> { const v=z.object({canonical_cwd:z.string(),milestone_id:z.string(),existing_thread_id:z.string(),user_intent:z.string(),confirmed:z.boolean().default(false)}).strict().parse(raw); const {confirmed,...base}=v; return confirmed?this.activate({...base,confirmed:true}):this.preview(base); }
  public async previewCompletion(raw:unknown):Promise<Record<string,unknown>> { const ctx=await this.context(raw); return {ok:true,confirmation_required:true,milestone_id:ctx.task.milestone_id, validation_commands:ctx.task.validation_commands}; }
  public async complete(raw:unknown):Promise<Record<string,unknown>> { const v=z.object({canonical_cwd:z.string(),milestone_id:z.string(),existing_thread_id:z.string(),user_intent:z.string(),outcome:z.enum(["ACCEPTED","NEEDS_REWORK"]),confirmed:z.literal(true)}).strict().parse(raw); const ctx=await this.context(v); const evidence=await this.verify(ctx.cwd,ctx.task.validation_commands); const outcome=evidence.every(x=>x.exit_code===0)?v.outcome:"NEEDS_REWORK"; if(v.outcome==="ACCEPTED"&&outcome!=="ACCEPTED") throw new Error("validation did not pass; ACCEPTED is forbidden"); const loaded=await this.registry.load(ctx.cwd); const record=loaded.registry.milestones[ctx.task.milestone_id]!; record.status=outcome; record.updated_at=this.now().toISOString(); for(const child of Object.values(loaded.registry.milestones)) if(outcome==="ACCEPTED"&&child.plan_snapshot.dependencies.includes(ctx.task.milestone_id)&&child.status==="WAITING") child.status="READY"; loaded.registry.updated_at=this.now().toISOString(); const audit=path.join(ctx.cwd,".project-capsule","execution-audit",`${ctx.task.milestone_id}-${Date.now()}.json`); await mkdir(path.dirname(audit),{recursive:true}); await writeFile(audit,JSON.stringify({milestone_id:ctx.task.milestone_id,outcome,evidence},null,2)+"\n","utf8"); await this.registry.save(loaded.registry); const p=this.grantPath(ctx.cwd,ctx.task.milestone_id); try { const g=GrantSchema.parse(JSON.parse(await readFile(p,"utf8"))); await writeFile(p,JSON.stringify({...g,status:"CONSUMED"},null,2)+"\n","utf8"); } catch {} return {ok:true,milestone_id:ctx.task.milestone_id,outcome,evidence_file:audit}; }
  private async context(raw:unknown) { const v=z.object({canonical_cwd:z.string(),milestone_id:z.string(),existing_thread_id:z.string(),user_intent:z.string()}).passthrough().parse(raw); const cwd=await canonicalizeProjectCwd(v.canonical_cwd); const plan=await validateProjectPlan(JSON.parse(await readFile(path.join(cwd,".project-capsule","plan-source.json"),"utf8"))); const task=plan.threads.find(x=>x.milestone_id===v.milestone_id); if(!task) throw new Error("unknown milestone"); const loaded=await this.registry.load(cwd); if(reconcileMilestoneStates(loaded.registry)) await this.registry.save(loaded.registry); const rec=loaded.registry.milestones[v.milestone_id]; if(!rec||rec.thread_id!==v.existing_thread_id) throw new Error("milestone and existing_thread_id do not match registry"); if(rec.milestone_status!=="READY") throw new Error("milestone is not READY"); if(task.dependencies.some(id=>loaded.registry.milestones[id]?.milestone_status!=="ACCEPTED")) throw new Error("dependencies are not ACCEPTED"); await this.app.readThread(v.existing_thread_id,true); return {cwd,plan,task,threadId:v.existing_thread_id,allowed:this.derive(cwd,task)}; }
  private derive(cwd:string,task:MilestoneTask) { const candidates=task.allowed_paths.length?task.allowed_paths:(task.milestone_id==="M0"?M0_TEMPLATE:[]); if(!candidates.length) throw new Error("no safe execution scope can be derived"); return candidates.map(x=>{if(validateProjectRelativePath(x)!==null||FORBIDDEN.some(f=>x===f||x.startsWith(f+"/")))throw new Error("unsafe derived path"); const absolute=path.resolve(cwd,x);if(!isPathInside(cwd,absolute))throw new Error("derived path escapes project");return absolute;}); }
  private grant(ctx:Awaited<ReturnType<MilestoneActivationService["context"]>>,status:Grant["status"]):Grant { const n=this.now(); return {milestone_id:ctx.task.milestone_id,thread_id:ctx.threadId,canonical_cwd:ctx.cwd,plan_digest:ctx.plan.plan_digest,task_digest:digestTask(ctx.task),allowed_paths:ctx.allowed,forbidden_paths:FORBIDDEN,sandbox_mode:"workspace-write",network_policy:"disabled",approval_policy:"on-request",granted_at:n.toISOString(),expires_at:new Date(n.getTime()+TTL).toISOString(),activation_operation_id:randomUUID(),status}; }
  private grantPath(cwd:string,id:string){return path.join(cwd,".project-capsule","execution-grants",`${id}.json`)}
  private async writeGrant(cwd:string,g:Grant){const p=this.grantPath(cwd,g.milestone_id);await mkdir(path.dirname(p),{recursive:true});await writeFile(p,JSON.stringify(g,null,2)+"\n","utf8");}
  private async verify(cwd:string,commands:string[]){ const evidence=[] as Array<Record<string,unknown>>; for(const command of commands){if(/[|&;<>()`$\r\n]/u.test(command)) throw new Error("unsafe validation command"); const [file,...args]=command.trim().split(/\s+/u); if(!file) throw new Error("empty validation command"); const started_at=this.now().toISOString(); try { const result=await execFileAsync(file,args,{cwd,timeout:60_000,windowsHide:true,maxBuffer:64*1024}); evidence.push({command,started_at,ended_at:this.now().toISOString(),exit_code:0,stdout:String(result.stdout).slice(0,4000),stderr:String(result.stderr).slice(0,4000)}); } catch(error) { const e=error as {code?:number;stdout?:string;stderr?:string}; evidence.push({command,started_at,ended_at:this.now().toISOString(),exit_code:typeof e.code==="number"?e.code:-1,stdout:String(e.stdout??"").slice(0,4000),stderr:String(e.stderr??String(error)).slice(0,4000)}); } } return evidence; }
}
