import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { CapsuleService } from "../mcp-server/src/capsule-service.js";
import { MilestoneActivationService } from "../mcp-server/src/milestone-activation-service.js";
import { RegistryStore, createReservedRecord } from "../mcp-server/src/registry.js";
import { digestTask, expectedThreadName, validateProjectPlan } from "../mcp-server/src/plan-validator.js";
import { makePlan, makeTask } from "./test-helpers.js";
import { ActivationMockAppServer } from "./activation-mock-app-server.js";

async function fixture(){const cwd=await mkdtemp(path.join(tmpdir(),"activation-涓枃 ")); const tasks=[makeTask(0,{allowed_paths:[],validation_commands:["node --version"]}),makeTask(1,{dependencies:["M0"],initial_status:"WAITING"}),makeTask(2,{dependencies:["M1"],initial_status:"WAITING"})]; const capsule=new CapsuleService(); await capsule.orchestrate({...makePlan(cwd,tasks) as Record<string,unknown>,dry_run:false,confirmed:true}); const plan=await validateProjectPlan(makePlan(cwd,tasks)); const app=new ActivationMockAppServer(); const thread=app.seed(cwd); const store=new RegistryStore(); const loaded=await store.load(cwd,{projectName:"Unit Test Project"}); for(const task of tasks){const r=createReservedRecord({task,taskDigest:digestTask(task),projectPlanDigest:plan.plan_digest,expectedName:expectedThreadName(task),now:new Date().toISOString()}); r.thread_id=task.milestone_id==="M0"?thread.id:`thread-${task.milestone_id}`;r.status=task.milestone_id==="M0"?"READY":"WAITING";loaded.registry.milestones[task.milestone_id]=r;} await store.save(loaded.registry); return {cwd,app,service:new MilestoneActivationService(app),thread};}
describe("milestone activation contract",()=>{
 it("derives M0 scope, writes a grant, reuses its thread and starts workspace-write",async()=>{const f=await fixture();const base={canonical_cwd:f.cwd,milestone_id:"M0",existing_thread_id:f.thread.id,user_intent:"鎵ц M0"};const preview=await f.service.start({...base,confirmed:false}) as Record<string,unknown>;expect(preview.ok).toBe(true);const before=await readFile(path.join(f.cwd,".project-capsule","thread-plan.json"),"utf8");const result=await f.service.start({...base,confirmed:true});expect(result.status).toBe("ACTIVE");const grant=JSON.parse(await readFile(path.join(f.cwd,".project-capsule","execution-grants","M0.json"),"utf8"));expect(grant.allowed_paths).toContain(path.join(f.cwd,"SPEC.md"));expect(await readFile(path.join(f.cwd,".project-capsule","thread-plan.json"),"utf8")).toBe(before);expect(f.app.events.filter(x=>x.method==="thread/start")).toHaveLength(0);const turn=f.app.events.filter(x=>x.method==="turn/start").at(-1)!;expect(turn.params).toMatchObject({threadId:f.thread.id,approvalPolicy:"on-request",sandboxPolicy:{type:"workspaceWrite",networkAccess:false}});});
 it("rejects WAITING dependencies and completes accepted M0 by running verification",async()=>{const f=await fixture();await expect(f.service.preview({canonical_cwd:f.cwd,milestone_id:"M1",existing_thread_id:"thread-M1",user_intent:"鎵ц M1"})).rejects.toThrow("not READY");const input={canonical_cwd:f.cwd,milestone_id:"M0",existing_thread_id:f.thread.id,user_intent:"鎵ц M0"};await f.service.activate({...input,confirmed:true});const done=await f.service.complete({...input,outcome:"ACCEPTED",confirmed:true});expect(done.outcome).toBe("ACCEPTED");const registry=await new RegistryStore().load(f.cwd);expect(registry.registry.milestones.M1?.status).toBe("READY");expect(JSON.parse(await readFile(String(done.evidence_file),"utf8"))).toHaveProperty("evidence");});
});

